# general settings
name: ESRT_x2
model_type: SRModel
scale: 2
num_gpu: 1 # set num_gpu: 0 for cpu mode
manual_seed: 1

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: PairedImageDataset
    dataroot_gt: datasets/DIV2K/DIV2K_train_HR
    dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic/X2
    filename_tmpl: "{}x2"
    io_backend:
      type: disk

    gt_size: 96
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 3
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 10
    prefetch_mode: ~

  val:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: datasets/Set5/GTmod12
    dataroot_lq: datasets/Set5/LRbicx2
    io_backend:
      type: disk

# network structures
network_g:
  type: ESRT
  upscaling_factor: 2

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4

  # scheduler:
  #   type: StepLR
  #   step_size: 50000
  #   gamma: 0.5
  #   last_epoch: -1
  scheduler:
    type: MultiStepLR
    milestones: [10000, 20000, 30000, 40000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 500
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
# python basicsr/train.py -opt options/train/ESRT/train_ESRT_x2.yml
