# general settings
name: testsr_01
model_type: TESTSR01Model
scale: 2
num_gpu: 1 # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: PairedImageDataset
    dataroot_gt: datasets/DIV2K/DIV2K_train_HR
    dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic/X2
    #    (for lmdb)
    # dataroot_gt: ./datasets/DF2K/DF2K_HR_sub.lmdb
    # dataroot_lq: ./datasets/DF2K/DF2K_train_LR_bicubic_X2_sub.lmdb
    filename_tmpl: "{}x2"
    io_backend:
      type: disk

    gt_size: 96
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 3
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: ./datasets/Set5/GTmod12
    dataroot_lq: ./datasets/Set5/LRbicx2
    io_backend:
      type: disk

# network structures
network_g:
  type: TESTSR01

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state:

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4

  scheduler:
    type: StepLR
    step_size: 10000
    gamma: 0.5
    last_epoch: -1

  total_iter: 50000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 50
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true
    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 2
      test_y_channel: true

# logging settings
logger:
  print_freq: 10
  save_checkpoint_freq: !!float 10000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~
    entity: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
# python basicsr/train.py -opt options/train/TESTSR/train_TESTSR01_x2.yml
