hparams = {'binary_data_dir': 'data/binary/df2k4x',
           'work_dir': 'checkpoints/xxx',
           'infer': False, 'seed': 1234, 'debug': False,
           'save_codes': ['configs', 'models', 'tasks', 'utils'],
           'ds_workers': 1,
           'endless': False,
           'print_nan_grads': False,
           'load_ckpt': '/kaggle/input/srdiff-pretrain-rrdb/pytorch/srdiff-pretrained-rrdb/1/pretrained_rrdb.pth',

           'save_best': True,
           'num_ckpt_keep': 100,
           'clip_grad_norm': 10,
           'accumulate_grad_batches': 1,
           'tb_log_interval': 100,
           'num_sanity_val_steps': 4,
           'check_val_every_n_epoch': 10,
           'val_check_interval': 4000,
           'valid_monitor_key': 'val_loss',
           'valid_monitor_mode': 'min',
           'max_epochs': 1000,
           'max_updates': 400000,
           'amp': False, 'batch_size': 64, 'eval_batch_size': 1, 'num_workers': 8,
           'test_input_dir': '',
           'resume_from_checkpoint': 0,
           'base_config': ['./diffsr_base.yaml', './df2k4x.yaml'],
           'data_interp': 'bicubic',
           'data_augmentation': False,
           'test_batch_size': 1, 'valid_steps': 4,
           'test_save_png': True,
           'gen_dir_name': '', 'beta_schedule': 'cosine', 'beta_s': 0.008, 'beta_end': 0.02, 'hidden_size': 64, 'timesteps': 100,
           'res': True, 'res_rescale': 2.0, 'up_input': False, 'use_wn': False, 'gn_groups': 0, 'use_rrdb': True,
           'rrdb_num_block': 8, 'rrdb_num_feat': 32, 'rrdb_ckpt': 'pretrained/rrdb_df_1', 'unet_dim_mults': '1|2|3|4',
           'clip_input': True, 'denoise_fn': 'unet', 'use_attn': False, 'aux_l1_loss': True, 'aux_ssim_loss': False,
           'aux_percep_loss': False, 'loss_type': 'l1', 'pred_noise': True, 'weight_init': False, 'fix_rrdb': True,
           'lr': 0.0002, 'decay_steps': 200000, 'style_interp': False, 'save_intermediate': False, 'show_training_process': False,
           'print_arch': False, 'patch_size': 160, 'crop_size': 320, 'thresh_size': 160, 'test_crop_size': [2040, 2040],
           'test_thresh_size': 0, 'sr_scale': 4, 'trainer_cls': 'tasks.srdiff_df2k.SRDiffDf2k', 'validate': False, 'exp_name': 'xxx'}

