# general settings
name: test_SRDiff_x4
model_type: SRDiffModel
scale: 4
num_gpu: 1 # set num_gpu: 0 for cpu mode
manual_seed: 1234

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: PairedImageDataset
    dataroot_gt: datasets/DF2K/DF2K_train_HR_sub.lmdb
    dataroot_lq: datasets/DF2K/DF2K_train_LR_bicubic_X4_sub.lmdb
    # dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub
    # dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic/X4_sub
    filename_tmpl: "{}"
    io_backend:
      #type: disk
      type: lmdb

    gt_size: 160
    use_hflip: true
    use_rot: true
    mean: [0.5, 0.5, 0.5]
    std: [0.5, 0.5, 0.5]

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 3 #change
    batch_size_per_gpu: 16 #change
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: Set14 #change
    type: PairedImageDataset
    dataroot_gt: ./datasets/Set14/GTmod12 #change
    dataroot_lq: ./datasets/Set14/LRbicx4 #change
    io_backend:
      type: disk

# network structures
network_g:
  type: SRDiff

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state:

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.999]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [400000]
    restart_weights: [1]
    eta_min: !!float 1e-4

  total_iter: 400000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: FakeLoss

# validation settings
val:
  val_freq: !!float 5000 #change
  save_img: false
  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true
    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 2
      test_y_channel: true

# logging settings
logger:
  print_freq: 100 #change
  save_checkpoint_freq: !!float 10000 #5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~
    entity: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
# python basicsr/train.py -opt options/train/SRDiff/train_SRDiff_x4.yml
